# Agent
algorithm : "DQN"
EPISODES : 1000

# Environment
environment : "TrafficEnv"
RENDER_MODE : "sumo"

# Run
DEVICE : cpu
SEED : 0
mode : "test"

#Hyperparameters
ALPHA : 0.0001
GAMMA : 0.99
EPSILON : 1.0
EPSILON_DECAY : 0.9975415
EPSILON_THRESHOLD: 0.1

#Save
PATH : "../algorithms/neural_networks/models/nm"
#Load
PATH_TEST : "../algorithms/neural_networks/models/TrafficEnv_DQN_1740681227.8100357_4.pth"
